# .github/workflows/linkcheck.yml
name: Link Check
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --accept 200,429 --exclude-path assets/docs --exclude-mail
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}